name: 'Cleanup - AWS Resources'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para destruir (dev ou prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  cleanup:
    name: 'Cleanup AWS Resources - ${{ github.event.inputs.environment }}'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}-destroy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Set Variables for Environment
      id: vars
      run: |
        if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
          echo "backend=prod.hcl" >> $GITHUB_OUTPUT
          echo "tfvars=prod.tfvars" >> $GITHUB_OUTPUT
        else
          echo "backend=np.hcl" >> $GITHUB_OUTPUT
          echo "tfvars=dev.tfvars" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Init
      run: terraform init -backend-config=backend/${{ steps.vars.outputs.backend }} -upgrade

    - name: Terraform Destroy
      run: terraform destroy -var-file=${{ steps.vars.outputs.tfvars }} -auto-approve
